sudo: required

language: php
php:
  - 7.2

before_install:
  - echo "Before install script!"

install:
  - echo "Installation script!"

before_script:
  - echo "Before script!"

script:
  - echo $TRAVIS_ENV_VAR
  - composer install
  - php vendor/bin/phpunit tests

after_success:
  - echo "success!!!"

after_failure:
  - echo "failure!!!"

before_deploy:
  - echo "Before deploy!"

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: travis_ci

after_deploy:
  - echo "After deploy"

after_script:
  - echo "After script!"

branches:
  only:
    - travis_ci

notifications:
  slack: phpbsa:R4wvQRE9ZpV3pA3bcOVUj6Wj
  on_success: always
  on_failure: always
  template:
    - "%{repository_slug} (%{commit}) : %{message} %{foo} "
    - "Build details: %{build_url}"